name: xmusic
description: An Open Source Music Player App.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.2.1+121

environment:
  sdk: ^3.7.0

dependencies:
  app_links: ^6.4.0
  audio_service: ^0.18.17
  audiotagger:
    git:
      url: https://github.com/Envoy-Z-lab-lav/Audiotagger.git
      ref: 9d32f33
  # bitsdojo_window: ^0.1.1+1 #For Desktops
  cached_network_image: ^3.3.1
  carousel_slider_plus: ^7.1.0
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  dart_des: ^1.0.2
  device_info_plus: ^11.3.3
  # ffmpeg_kit_flutter_audio: ^6.0.3
  file_picker: ^9.2.2
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_archive: ^6.0.0
  # flutter_downloader: ^1.7.1
  flutter_localizations:
    sdk: flutter
  flutter_lyric: ^2.0.4+6
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  home_widget: ^0.7.0+1
  html_unescape: ^2.0.0
  just_audio: ^0.9.46
  # Discontinued, Use just_audio_windows instead.
  # For Linux use just_audio_mpv.
  # just_audio_libwinmedia: ^0.0.4 # For windows and linux.
  logging: ^1.3.0
  marquee:
    git:
      url: https://github.com/hendrilmendes/marquee.git
      ref: cfe2637
  material_design_icons_flutter: 5.0.5955-rc.1
  metadata_god: ^0.5.2+1
  on_audio_query: ^2.9.0
  package_info_plus: ^8.3.0
  palette_generator: ^0.3.3+6
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  persistent_bottom_nav_bar: ^6.2.1
  receive_sharing_intent: ^1.8.1
  share_plus: ^10.1.4
  sizer: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.3.1
  uuid: ^3.0.7
  # workmanager: ^0.5.1
  youtube_explode_dart: ^2.4.0-dev.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  msix: ^3.16.8

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets to the application.
    - assets/

msix_config:
  display_name: XMusic
  publisher_display_name: Hendril Mendes
  identity_name: com.github.hendrilmendes.music
  icons_background_color: transparent
  logo_path: assets/ic_launcher.png
  file_extension: .mp3, .m4a
