// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDakUa8vjQ0TiuBhdiIMXiNdTqjYG4ZN_M',
    appId: '1:744134867766:android:4f0f40ee0b575ee8921197',
    messagingSenderId: '744134867766',
    projectId: 'xmusic-f14de',
    storageBucket: 'xmusic-f14de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4QxyO15rv-HPsBykTviRObmJtJpSWuko',
    appId: '1:744134867766:ios:2d4a5cb496324da2921197',
    messagingSenderId: '744134867766',
    projectId: 'xmusic-f14de',
    storageBucket: 'xmusic-f14de.firebasestorage.app',
    iosBundleId: 'com.github.hendrilmendes.music',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4QxyO15rv-HPsBykTviRObmJtJpSWuko',
    appId: '1:744134867766:ios:2d4a5cb496324da2921197',
    messagingSenderId: '744134867766',
    projectId: 'xmusic-f14de',
    storageBucket: 'xmusic-f14de.firebasestorage.app',
    iosBundleId: 'com.github.hendrilmendes.music',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD628PONL3izNWvPfG3RLsLJwE_zl9PdA0',
    appId: '1:744134867766:web:35c684316986c86a921197',
    messagingSenderId: '744134867766',
    projectId: 'xmusic-f14de',
    authDomain: 'xmusic-f14de.firebaseapp.com',
    storageBucket: 'xmusic-f14de.firebasestorage.app',
    measurementId: 'G-L1JH5QQP38',
  );
}
